SET NAMES UTF8;
SET SQL DIALECT 3;


/* EDUCATIONS */
CREATE TABLE EDUCATIONS (
    ID_EDUCATION INTEGER NOT NULL,
    NAME_EDUCATION VARCHAR(60),
    TYPE_EDUCTAION VARCHAR(60),
    DATE_START DATE,
    DATE_END DATE,
    RESULT VARCHAR(60),
    ID_USER INTEGER);

/* USER_SKILLS */
CREATE TABLE USER_SKILLS (
    ID INTEGER NOT NULL,
    ID_SKILL INTEGER,
    MARK_SKILL INTEGER,
    USER_ID INTEGER,
    STATUS VARCHAR(30));

/* EXPERIENCES */
CREATE TABLE EXPERIENCES (
    ID INTEGER NOT NULL,
    TYPE VARCHAR(60),
    NAME_COMPANY VARCHAR(60),
    POST VARCHAR(60),
    DATE_START DATE,
    DATE_END DATE,
    ID_USER INTEGER);

/* RATING */
CREATE TABLE RATING (
    ID_RATING INTEGER NOT NULL,
    "DATE_rating" DATE,
    TYPE_RATING VARCHAR(50),
    "LEVEL_rating" DOUBLE PRECISION,
    USER_ID INTEGER,
    ID_SKILL INTEGER);

/* SKILLS */
CREATE TABLE SKILLS (
    ID_SKILL INTEGER NOT NULL,
    NAME_SKILL VARCHAR(60));

/* USER_COMPILATION */
CREATE TABLE USER_COMPILATION (
    ID_USER_COMPILATION INTEGER NOT NULL,
    ID_COMPILATION INTEGER,
    ID_USER INTEGER);

/* COMPILATION */
CREATE TABLE COMPILATION (
    ID_COMPILATION INTEGER NOT NULL,
    NAME_COMPILATION VARCHAR(60),
    "DATE" DATE);

/* LOGS */
CREATE TABLE LOGS (
    ID_LOG INTEGER NOT NULL,
    TYPE_LOG VARCHAR(60),
    DESCRIPTION_LOG VARCHAR(100),
    LOG_ID INTEGER);

/* NOTIFICATIONS */
CREATE TABLE NOTIFICATIONS (
    ID_NOTIFICATION INTEGER NOT NULL,
    ID_USER INTEGER,
    DESCRIPTION VARCHAR(200),
    "DATE" DATE);

/* USERS */
CREATE TABLE USERS (
    ID_USER INTEGER NOT NULL,
    NAME_USER VARCHAR(60),
    SURNAME_USER VARCHAR(60),
    PATRONYMIC_USER VARCHAR(60),
    PHONE_USER VARCHAR(20),
    EMAIL_USER VARCHAR(60),
    PASSWORD_USER VARCHAR(40),
    ROLE_USER VARCHAR(20),
    DATE_CREATE DATE,
    PIN VARCHAR(60));

/* USER_ROLES */
CREATE TABLE USER_ROLES (
    ID_USER_ROLE INTEGER NOT NULL,
    ID_USER INTEGER,
    NAME_ROLE_BEFORE VARCHAR(60),
    NAME_ROLE_AFTER VARCHAR(60));

/* CONFIRMATIONS */
CREATE TABLE CONFIRMATIONS (
    ID_CONFIRMATION INTEGER NOT NULL,
    USER_FROM INTEGER,
    USER_TO INTEGER,
    ID_SKILL INTEGER,
    STATUS VARCHAR(60),
    "DATE" DATE);

/* EDUCATIONS.PK_EDUCATIONS */
ALTER TABLE EDUCATIONS
ADD CONSTRAINT PK_EDUCATIONS PRIMARY KEY (ID_EDUCATION);

/* USER_SKILLS.PK_USER_SKILLS */
ALTER TABLE USER_SKILLS
ADD CONSTRAINT PK_USER_SKILLS PRIMARY KEY (ID);

/* EXPERIENCES.PK_EXPERIENCES */
ALTER TABLE EXPERIENCES
ADD CONSTRAINT PK_EXPERIENCES PRIMARY KEY (ID);

/* RATING.PK_RATING */
ALTER TABLE RATING
ADD CONSTRAINT PK_RATING PRIMARY KEY (ID_RATING);

/* SKILLS.PK_SKILLS */
ALTER TABLE SKILLS
ADD CONSTRAINT PK_SKILLS PRIMARY KEY (ID_SKILL);

/* USER_COMPILATION.PK_USER_COMPILATION */
ALTER TABLE USER_COMPILATION
ADD CONSTRAINT PK_USER_COMPILATION PRIMARY KEY (ID_USER_COMPILATION);

/* COMPILATION.PK_COMPILATION */
ALTER TABLE COMPILATION
ADD CONSTRAINT PK_COMPILATION PRIMARY KEY (ID_COMPILATION);

/* LOGS.PK_LOGS */
ALTER TABLE LOGS
ADD CONSTRAINT PK_LOGS PRIMARY KEY (ID_LOG);

/* NOTIFICATIONS.PK_NOTIFICATIONS */
ALTER TABLE NOTIFICATIONS
ADD CONSTRAINT PK_NOTIFICATIONS PRIMARY KEY (ID_NOTIFICATION);

/* USERS.PK_USERS */
ALTER TABLE USERS
ADD CONSTRAINT PK_USERS PRIMARY KEY (ID_USER);

/* USER_ROLES.PK_USER_ROLES */
ALTER TABLE USER_ROLES
ADD CONSTRAINT PK_USER_ROLES PRIMARY KEY (ID_USER_ROLE);

/* CONFIRMATIONS.PK_CONFIRMATIONS */
ALTER TABLE CONFIRMATIONS
ADD CONSTRAINT PK_CONFIRMATIONS PRIMARY KEY (ID_CONFIRMATION);

/* USERS.UQ_USERS_1 */
ALTER TABLE USERS
ADD CONSTRAINT UQ_USERS_1 UNIQUE (EMAIL_USER);

/* USERS.UQ_USERS_2 */
ALTER TABLE USERS
ADD CONSTRAINT UQ_USERS_2 UNIQUE (PHONE_USER);

/* EDUCATIONS.FK_EDUCATIONS_1 */
ALTER TABLE EDUCATIONS
ADD CONSTRAINT FK_EDUCATIONS_1 FOREIGN KEY (ID_USER) REFERENCES USERS (ID_USER);

/* USER_SKILLS.FK_USER_SKILLS_1 */
ALTER TABLE USER_SKILLS
ADD CONSTRAINT FK_USER_SKILLS_1 FOREIGN KEY (ID_SKILL) REFERENCES SKILLS (ID_SKILL);

/* USER_SKILLS.FK_USER_SKILLS_2 */
ALTER TABLE USER_SKILLS
ADD CONSTRAINT FK_USER_SKILLS_2 FOREIGN KEY (USER_ID) REFERENCES USERS (ID_USER);

/* EXPERIENCES.FK_EXPERIENCES_1 */
ALTER TABLE EXPERIENCES
ADD CONSTRAINT FK_EXPERIENCES_1 FOREIGN KEY (ID_USER) REFERENCES USERS (ID_USER);

/* RATING.FK_RATING_1 */
ALTER TABLE RATING
ADD CONSTRAINT FK_RATING_1 FOREIGN KEY (USER_ID) REFERENCES USERS (ID_USER);

/* RATING.FK_RATING_2 */
ALTER TABLE RATING
ADD CONSTRAINT FK_RATING_2 FOREIGN KEY (ID_SKILL) REFERENCES SKILLS (ID_SKILL);

/* USER_COMPILATION.FK_USER_COMPILATION_1 */
ALTER TABLE USER_COMPILATION
ADD CONSTRAINT FK_USER_COMPILATION_1 FOREIGN KEY (ID_USER) REFERENCES USERS (ID_USER);

/* USER_COMPILATION.FK_USER_COMPILATION_2 */
ALTER TABLE USER_COMPILATION
ADD CONSTRAINT FK_USER_COMPILATION_2 FOREIGN KEY (ID_COMPILATION) REFERENCES COMPILATION (ID_COMPILATION);

/* NOTIFICATIONS.FK_NOTIFICATIONS_1 */
ALTER TABLE NOTIFICATIONS
ADD CONSTRAINT FK_NOTIFICATIONS_1 FOREIGN KEY (ID_USER) REFERENCES USERS (ID_USER);

/* USER_ROLES.FK_USER_ROLES_1 */
ALTER TABLE USER_ROLES
ADD CONSTRAINT FK_USER_ROLES_1 FOREIGN KEY (ID_USER) REFERENCES USERS (ID_USER);

/* CONFIRMATIONS.FK_CONFIRMATIONS_1 */
ALTER TABLE CONFIRMATIONS
ADD CONSTRAINT FK_CONFIRMATIONS_1 FOREIGN KEY (USER_FROM) REFERENCES USERS (ID_USER);

/* CONFIRMATIONS.FK_CONFIRMATIONS_2 */
ALTER TABLE CONFIRMATIONS
ADD CONSTRAINT FK_CONFIRMATIONS_2 FOREIGN KEY (USER_TO) REFERENCES USERS (ID_USER);

/* CONFIRMATIONS.FK_CONFIRMATIONS_3 */
ALTER TABLE CONFIRMATIONS
ADD CONSTRAINT FK_CONFIRMATIONS_3 FOREIGN KEY (ID_SKILL) REFERENCES SKILLS (ID_SKILL);

